# Generated by Django 4.2.15 on 2026-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0005_achievement_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_config',
            field=models.JSONField(blank=True, default=dict, help_text='purchased_events: {"event_ids": [9, 10, 17]} (AND). volunteer_at_events: {"event_ids": [14, 7, 4, 1], "role": "transmutator", "must_be_used": true} (OR; role: transmutator | ranger | caos | mad).'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('purchased_events', 'Compró en eventos'), ('volunteer_at_events', 'Voluntario en eventos')], max_length=32),
        ),
    ]
