# Generated by Django 4.2.15 on 2026-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0006_achievement_volunteer_at_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_config',
            field=models.JSONField(blank=True, default=dict, help_text='purchased_events: {"event_ids": [9, 10, 17]} (AND). volunteer_at_events: {"role": "transmutator", "must_be_used": true} (cualquier evento; opcional event_ids para limitar; role: transmutator | ranger | caos | mad). attended_events: {"event_ids": [14, 7, 4, 1], "min_count": 2} (al menos N eventos distintos; must_be_used default true).'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('purchased_events', 'Compró en eventos'), ('volunteer_at_events', 'Voluntario en eventos'), ('attended_events', 'Asistió a eventos')], max_length=32),
        ),
    ]
