# Generated by Django 4.2.15 on 2026-08-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0007_achievement_attended_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['sort_order', 'name'], 'permissions': [('manage_achievements', 'Can manage achievements')], 'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AddField(
            model_name='userachievement',
            name='granted_manually',
            field=models.BooleanField(default=False, help_text='True cuando un admin lo asignó (o re-asignó) a mano.'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='revoked',
            field=models.BooleanField(default=False, help_text='Si True, el logro no cuenta como desbloqueado y el auto-unlock no lo re-otorga.'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('purchased_events', 'Compró en eventos'), ('volunteer_at_events', 'Voluntario en eventos'), ('attended_events', 'Asistió a eventos')], help_text='Vacío = solo asignación manual (sin auto-unlock).', max_length=32, null=True),
        ),
    ]
