# Generated by Django 3.2.9 on 2023-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='Only 1 event can be active at a time')),
                ('name', models.CharField(max_length=255)),
                ('has_volunteers', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('max_transfer_datetime', models.DateTimeField()),
                ('header_image', models.ImageField(help_text='Dimensions: 1666px x 500px', upload_to='events/heros')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('pre_ticket_form_info', models.TextField(help_text='Will appear before the buy ticket form')),
                ('email_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
