# Generated by Django 3.2.9 on 2023-04-17 19:27

from django.db import migrations
from django.utils.timezone import now


def add_first_event(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model("events", "Event")
    today = now()
    Event.objects.create(
        active=True,
        name="Fuego Austral 2023",
        has_volunteers=True,
        start=today,
        end=today,
        transfers_enabled_until=today,

        # homepage
        header_image='',
        title="Fuego Austral 2023",
        description="<p> Fuego Austral 2023</p>",

        # ticket form
        pre_ticket_form_info="<p>Info</p>",

        # ticket email
        email_info="<p>Info</p>",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_max_transfer_datetime_event_transfers_enabled_until'),
    ]

    operations = [
        migrations.RunPython(add_first_event),
    ]
