# Generated by Django 3.2.9 on 2023-04-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230417_1627'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active'),
        ),
    ]
