# Generated by Django 3.2.9 on 2023-09-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_header_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_multiple_tickets',
            field=models.BooleanField(default=False, help_text='If unchecked, only the chepeast ticket will be shown.'),
        ),
    ]
