# Generated by Django 3.2.9 on 2023-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_show_multiple_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
