# Generated by Django 3.2.9 on 2024-04-21 06:25

from django.db import migrations

def add_header_image_to_first_event(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    event = Event.objects.get(active=True)
    event.header_image = 'events/heros/no-image.jpg'
    event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_max_tickets'),
    ]

    operations = [
        migrations.RunPython(add_header_image_to_first_event),
    ]
