# Generated by Django 4.2.15 on 2024-08-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_header_image_to_first_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_order',
            field=models.IntegerField(default=5),
        ),
    ]
