# Generated by Django 4.2.15 on 2024-10-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_max_tickets_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers_enabled_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
