# Generated by Django 4.2.15 on 2025-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_volunteers_enabled_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_must_be_registered',
            field=models.BooleanField(default=True, help_text='If checked, all attendees must be registered users'),
        ),
    ]
