# Generated by Django 4.2.15 on 2025-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_attendee_must_be_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the event', max_length=255),
        ),
    ] 