# Generated by Django 4.2.15 on 2025-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, help_text='URL for the event location (e.g. Google Maps link)', max_length=500),
        ),
    ]
