# Generated by Django 4.2.15 on 2025-09-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_location_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_tickets_sold_report', 'Can view tickets sold report')]},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_active',
        ),
        migrations.AddField(
            model_name='event',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Main event displayed at /'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the event', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, help_text='Event is active and can be accessed'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='unique_main_event'),
        ),
    ]
