# Generated by Django 4.2.15 on 2025-09-11 00:30

from django.db import migrations
from django.utils.text import slugify


def populate_slugs_and_set_main_event(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    # Get all events
    events = Event.objects.all()
    
    if events.exists():
        # Set the first active event as main
        main_event = events.filter(active=True).first()
        if main_event:
            main_event.is_main = True
            main_event.save()
        
        # Populate slugs for all events
        for event in events:
            if not event.slug:
                event.slug = slugify(event.name)
                event.save()


def reverse_populate_slugs_and_set_main_event(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    # Clear slugs and main event flag
    Event.objects.update(slug=None, is_main=False)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_add_slug_and_main_event_fields'),
    ]

    operations = [
        migrations.RunPython(
            populate_slugs_and_set_main_event,
            reverse_populate_slugs_and_set_main_event
        ),
    ]
