# Generated by Django 4.2.24 on 2025-09-12 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_populate_slugs_and_set_main_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users who can administer this event', related_name='admin_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
