# Generated by Django 4.2.24 on 2025-09-13 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_event_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_scanner',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the scanner for this event', related_name='scanner_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
