# Generated by Django 4.2.24 on 2025-09-15 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_event_access_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_caja',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the caja for this event', related_name='caja_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
