# Generated by Django 4.2.24 on 2025-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_access_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum venue capacity (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_occupancy',
            field=models.PositiveIntegerField(default=0, help_text='Current venue occupancy'),
        ),
    ]
