# Generated by Django 4.2.24 on 2025-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_venue_capacity_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_occupancy',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees_left',
            field=models.PositiveIntegerField(default=0, help_text='Number of attendees who have left the venue'),
        ),
    ]
