# Generated by Django 4.2.24 on 2025-11-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_attendees_left_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Título del término y condición', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada (opcional)', null=True)),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='events.event')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
                'ordering': ['order', 'id'],
            },
        ),
    ]
