# Generated by Django 4.2.24 on 2025-11-19 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0064_directtickettemplate_email'),
        ('events', '0021_eventtermsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTermsAndConditionsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Orden asociada a esta aceptación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.order')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='events.eventtermsandconditions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceptación de Términos y Condiciones',
                'verbose_name_plural': 'Aceptaciones de Términos y Condiciones',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'term')},
            },
        ),
    ]
