# Generated by Django 4.2.24 on 2025-11-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_eventtermsandconditionsacceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='header_bg_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pre_ticket_form_info',
        ),
    ]
