# Generated by Django 4.2.24 on 2025-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtermsandconditions',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the term', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtermsandconditions',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada (opcional, puede contener HTML)', null=True),
        ),
    ]
