# Generated by Django 4.2.24 on 2025-12-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0024_add_slug_to_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de grupo (ej: ARTE, CAMP, CAOS)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del tipo de grupo', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo de grupo está activo')),
            ],
            options={
                'verbose_name': 'Tipo de Grupo',
                'verbose_name_plural': 'Tipos de Grupo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre del grupo', max_length=255)),
                ('ingreso_anticipado_amount', models.PositiveIntegerField(default=0, help_text='Cantidad máxima de personas que pueden tener ingreso anticipado')),
                ('event', models.ForeignKey(help_text='Evento al que pertenece el grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='events.event')),
                ('lider', models.ForeignKey(help_text='Usuario líder del grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(help_text='Tipo de grupo', on_delete=django.db.models.deletion.RESTRICT, related_name='grupos', to='events.grupotipo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['tipo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingreso_anticipado', models.BooleanField(default=False, help_text='Indica si el miembro tiene ingreso anticipado')),
                ('grupo', models.ForeignKey(help_text='Grupo al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='events.grupo')),
                ('user', models.ForeignKey(help_text='Usuario miembro del grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupo',
                'ordering': ['-ingreso_anticipado', 'user__email'],
                'unique_together': {('grupo', 'user')},
            },
        ),
    ]
