# Generated by Django 4.2.24 on 2025-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_grupotipo_grupo_grupomiembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ingreso_anticipado_desde',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora desde la cual se puede hacer ingreso anticipado', null=True),
        ),
    ]
