# Generated by Django 4.2.24 on 2025-12-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_grupo_ingreso_anticipado_desde'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupomiembro',
            options={'ordering': ['-ingreso_anticipado', '-late_checkout', 'user__email'], 'verbose_name': 'Miembro de Grupo', 'verbose_name_plural': 'Miembros de Grupo'},
        ),
        migrations.AddField(
            model_name='grupo',
            name='late_checkout_amount',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad máxima de personas que pueden tener late checkout'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='late_checkout_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora hasta la cual se puede hacer late checkout', null=True),
        ),
        migrations.AddField(
            model_name='grupomiembro',
            name='late_checkout',
            field=models.BooleanField(default=False, help_text='Indica si el miembro tiene late checkout'),
        ),
    ]
