# Generated by Django 4.2.15 on 2026-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_grupomiembro_restriccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomiembro',
            name='ingreso_anticipado_fecha',
            field=models.DateField(blank=True, help_text='Fecha de ingreso anticipado (entre desde y fecha de inicio del evento)', null=True),
        ),
    ]
