# Generated by Django 4.2.15 on 2026-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_add_ingreso_anticipado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_transfer_notifications',
            field=models.BooleanField(default=False, help_text='If checked, transfer notification emails will be sent for this event'),
        ),
    ]
