# Generated by Django 4.2.15 on 2026-01-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0030_event_send_transfer_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(help_text='Usuario responsable del grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
