# Generated by Django 4.2.15 on 2026-01-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_grupo_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ingreso_anticipado_limite_carga',
            field=models.DateTimeField(blank=True, help_text='Fecha límite hasta la cual se pueden cargar o modificar ingresos anticipados. Si es null, no hay límite.', null=True),
        ),
    ]
