# Generated by Django 4.2.15 on 2026-08-14 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0039_eventrequest_end_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('planned', 'Obra inscripta'), ('popup', 'Obra espontánea (popup)')], default='planned', max_length=10, verbose_name='Modalidad')),
                ('title', models.CharField(max_length=120, verbose_name='Nombre de la obra')),
                ('proposal', models.TextField(verbose_name='Descripción de la propuesta')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='Dimensiones')),
                ('materials', models.TextField(blank=True, verbose_name='Materiales')),
                ('technical_needs', models.TextField(blank=True, verbose_name='Necesidades técnicas y energía')),
                ('safety_plan', models.TextField(blank=True, verbose_name='Seguridad y uso de fuego')),
                ('grant_requested', models.BooleanField(default=False, verbose_name='Quiero solicitar una beca')),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monto solicitado')),
                ('grant_budget', models.TextField(blank=True, verbose_name='Presupuesto y uso de los fondos')),
                ('grant_justification', models.TextField(blank=True, verbose_name='Por qué la beca hace posible la obra')),
                ('grant_status', models.CharField(choices=[('none', 'No solicitada'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'No aprobada')], default='none', max_length=10, verbose_name='Estado de la beca')),
                ('grant_report', models.TextField(blank=True, verbose_name='Rendición y resultado de la obra')),
                ('public_title', models.CharField(blank=True, max_length=80, verbose_name='Título para el desplegable')),
                ('public_description', models.CharField(blank=True, max_length=500, verbose_name='Descripción para el desplegable')),
                ('preferred_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación preferida')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso anticipado')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('crew', models.TextField(blank=True, verbose_name='Equipo que ingresa')),
                ('providers', models.TextField(blank=True, verbose_name='Proveedores y vehículos')),
                ('checkout_completed', models.BooleanField(default=False, verbose_name='Obra retirada y espacio limpio')),
                ('checkout_notes', models.TextField(blank=True, verbose_name='Notas de checkout')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_artworks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='events.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Obra de Arte',
                'verbose_name_plural': 'Obras de Arte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkGrantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='art/grant_reports')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_photos', to='events.artwork')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de rendición de beca',
                'verbose_name_plural': 'Fotos de rendición de becas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_opens', models.DateTimeField(blank=True, null=True, verbose_name='Apertura de inscripción')),
                ('registration_closes', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de inscripción')),
                ('proposal_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de propuesta')),
                ('grants_enabled', models.BooleanField(default=False, verbose_name='Becas habilitadas')),
                ('grant_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de becas')),
                ('guide_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de desplegable')),
                ('logistics_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de logística')),
                ('checkout_opens', models.DateTimeField(blank=True, null=True, verbose_name='Apertura de checkout')),
                ('checkout_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de checkout')),
                ('grant_report_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de rendición de becas')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_program', to='events.event')),
            ],
            options={
                'verbose_name': 'Programa de Arte',
                'verbose_name_plural': 'Programas de Arte',
            },
        ),
    ]
