# Generated by Django 4.2.15 on 2026-08-14 17:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import events.models
import uuid


def migrate_existing_art_data(apps, schema_editor):
    ArtProgram = apps.get_model('events', 'ArtProgram')
    Artwork = apps.get_model('events', 'Artwork')
    ArtworkGrantItem = apps.get_model('events', 'ArtworkGrantItem')
    ArtworkGrantPhoto = apps.get_model('events', 'ArtworkGrantPhoto')
    ArtworkPhoto = apps.get_model('events', 'ArtworkPhoto')

    current = ArtProgram.objects.filter(event__is_main=True).first() or ArtProgram.objects.order_by('-event__start').first()
    if current:
        ArtProgram.objects.filter(pk=current.pk).update(is_current=True)

    for artwork in Artwork.objects.all():
        updates = {}
        if artwork.submitted_at:
            updates['status'] = 'submitted'
        if artwork.checkout_completed:
            updates['checkout_requested_at'] = artwork.updated_at
        if updates:
            Artwork.objects.filter(pk=artwork.pk).update(**updates)
        if artwork.grant_amount:
            details = artwork.grant_budget or 'Presupuesto migrado del formulario anterior'
            ArtworkGrantItem.objects.create(
                artwork_id=artwork.pk,
                phase='budget',
                concept='Presupuesto migrado',
                details=details,
                amount=artwork.grant_amount,
                currency='ARS',
                exchange_rate=1,
                rate_date=timezone.localtime(artwork.submitted_at or artwork.created_at).date(),
                created_by_id=artwork.owner_id,
            )

    for photo in ArtworkGrantPhoto.objects.all():
        ArtworkPhoto.objects.create(
            artwork_id=photo.artwork_id,
            image=photo.image,
            stage='grant',
            uploaded_by_id=photo.uploaded_by_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0040_artwork_artworkgrantphoto_artprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkGrantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('budget', 'Presupuesto'), ('expense', 'Rendición')], max_length=8)),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('details', models.TextField(blank=True, verbose_name='Detalle')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto original')),
                ('currency', models.CharField(choices=[('ARS', 'Pesos argentinos (ARS)'), ('USD', 'Dólares estadounidenses (USD)')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cotización ARS por USD')),
                ('rate_date', models.DateField(verbose_name='Fecha de cotización o pago')),
                ('rate_source', models.CharField(blank=True, max_length=200, verbose_name='Fuente y tipo de cambio')),
            ],
            options={
                'verbose_name': 'Ítem de beca',
                'verbose_name_plural': 'Ítems de beca',
                'ordering': ['phase', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='art/gallery')),
                ('stage', models.CharField(choices=[('proposal', 'Propuesta'), ('process', 'Proceso'), ('final', 'Obra terminada'), ('grant', 'Rendición de beca')], default='process', max_length=10, verbose_name='Etapa')),
                ('caption', models.TextField(blank=True, verbose_name='Descripción o crédito')),
                ('publication_authorized', models.BooleanField(default=False, verbose_name='Autorizada para publicación')),
            ],
            options={
                'verbose_name': 'Foto de obra',
                'verbose_name_plural': 'Fotos de obras',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='artprogram',
            name='early_entry_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ingreso anticipado desde'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='early_entry_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupos de ingreso anticipado por obra'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Convocatoria anual vigente'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='late_checkout_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupos de late checkout por obra'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='late_checkout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Late checkout hasta'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='reminder_days',
            field=models.JSONField(blank=True, default=events.models.default_art_reminder_days, verbose_name='Días de anticipación para recordatorios'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='reminder_email_enabled',
            field=models.BooleanField(default=True, verbose_name='Recordatorios por email'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='reminder_whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='Recordatorios por WhatsApp'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='assigned_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación asignada'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='benefit_notes',
            field=models.TextField(blank=True, verbose_name='Notas del beneficio'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='benefit_status',
            field=models.CharField(choices=[('none', 'Sin evaluar'), ('eligible', 'Elegible'), ('granted', 'Otorgado'), ('ineligible', 'No elegible')], default='none', max_length=10, verbose_name='Beneficio para la próxima edición'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkout_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkout solicitado'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkout_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkout verificado'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkout_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_artwork_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='extinguishing_plan',
            field=models.TextField(blank=True, verbose_name='Plan y elementos de extinción'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='fire_details',
            field=models.TextField(blank=True, verbose_name='Combustible, cantidad y funcionamiento del fuego'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='grant_approved_amount_ars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monto aprobado en ARS'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='grant_decision_notes',
            field=models.TextField(blank=True, verbose_name='Devolución sobre la beca'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='grant_paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago de la beca'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='grant_payment_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referencia del pago'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='operations_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork', to='events.grupo'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='placement_notes',
            field=models.TextField(blank=True, verbose_name='Notas de placement'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='power_watts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Potencia eléctrica máxima (W)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='Devolución al equipo de la obra'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='safety_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de seguridad durante el evento'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'En revisión'), ('changes', 'Requiere cambios'), ('accepted', 'Aceptada'), ('rejected', 'No aceptada'), ('installed', 'Instalada'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], default='draft', max_length=12, verbose_name='Estado de la obra'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='uses_fire',
            field=models.BooleanField(default=False, verbose_name='La obra utiliza fuego'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkout_completed',
            field=models.BooleanField(default=False, verbose_name='Solicito verificar el retiro y limpieza'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='events.event'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='grant_status',
            field=models.CharField(choices=[('none', 'No solicitada'), ('pending', 'Pendiente'), ('info', 'Requiere información'), ('approved', 'Aprobada'), ('rejected', 'No aprobada'), ('paid', 'Pagada'), ('reported', 'Rendición enviada'), ('closed', 'Rendición aprobada')], default='none', max_length=10, verbose_name='Estado de la beca'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='proposal',
            field=models.TextField(blank=True, verbose_name='Descripción de la propuesta'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre de la obra'),
        ),
        migrations.AddConstraint(
            model_name='artprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_art_program'),
        ),
        migrations.AddField(
            model_name='artworkphoto',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.artwork'),
        ),
        migrations.AddField(
            model_name='artworkphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkinvitation',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.artwork'),
        ),
        migrations.AddField(
            model_name='artworkinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkgrantitem',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_items', to='events.artwork'),
        ),
        migrations.AddField(
            model_name='artworkgrantitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='artworkinvitation',
            constraint=models.UniqueConstraint(fields=('artwork', 'email'), name='unique_artwork_invitation_email'),
        ),
        migrations.AddConstraint(
            model_name='artworkgrantitem',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='art_grant_item_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='artworkgrantitem',
            constraint=models.CheckConstraint(check=models.Q(('exchange_rate__gt', 0)), name='art_grant_item_positive_rate'),
        ),
        migrations.AddConstraint(
            model_name='artworkgrantitem',
            constraint=models.CheckConstraint(check=models.Q(('currency', 'USD'), ('exchange_rate', 1), _connector='OR'), name='art_grant_item_ars_rate_one'),
        ),
        migrations.RunPython(migrate_existing_art_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='artwork',
            name='grant_amount',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='grant_budget',
        ),
        migrations.DeleteModel(
            name='ArtworkGrantPhoto',
        ),
    ]
