# Generated by Django 4.2.15 on 2026-08-14 18:11

from django.db import migrations, models
from django.core.files.storage import default_storage
import events.models


def move_art_photos_to_private_storage(apps, schema_editor):
    ArtworkPhoto = apps.get_model('events', 'ArtworkPhoto')
    private_storage = ArtworkPhoto._meta.get_field('image').storage
    if private_storage is default_storage:
        return
    for photo in ArtworkPhoto.objects.exclude(image=''):
        name = photo.image.name
        if private_storage.exists(name):
            if default_storage.exists(name):
                default_storage.delete(name)
            continue
        if default_storage.exists(name):
            with default_storage.open(name, 'rb') as source:
                private_storage.save(name, source)
            default_storage.delete(name)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_artworkgrantitem_artworkinvitation_artworkphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkphoto',
            name='image',
            field=models.ImageField(storage=events.models.private_art_storage, upload_to='art/gallery'),
        ),
        migrations.RunPython(move_art_photos_to_private_storage, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='artworkgrantitem',
            constraint=models.CheckConstraint(check=models.Q(('phase__in', ('budget', 'expense'))), name='art_grant_item_valid_phase'),
        ),
        migrations.AddConstraint(
            model_name='artworkgrantitem',
            constraint=models.CheckConstraint(check=models.Q(('currency__in', ('ARS', 'USD'))), name='art_grant_item_valid_currency'),
        ),
    ]
