# Generated by Django 4.2.15 on 2026-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_secure_art_finance_and_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkgrantitem',
            name='item_type',
            field=models.CharField(choices=[('materials', 'Materiales'), ('labor', 'Mano de obra'), ('service', 'Servicio'), ('other', 'Otro')], default='other', max_length=10, verbose_name='Tipo'),
        ),
    ]
