# Generated by Django 4.2.15 on 2026-08-14 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0043_classify_grant_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Proveedor o empresa')),
                ('contact_first_name', models.CharField(max_length=100, verbose_name='Nombre del contacto')),
                ('contact_last_name', models.CharField(max_length=100, verbose_name='Apellido del contacto')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('service_description', models.TextField(verbose_name='Servicio o materiales que entrega')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
            ],
            options={
                'verbose_name': 'Proveedor de obra',
                'verbose_name_plural': 'Proveedores de obra',
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkout_art_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_checkout_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Arte'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha general de ingreso anticipado'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha general de desarme y salida'),
        ),
        migrations.CreateModel(
            name='ArtworkProviderVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Auto'), ('van', 'Utilitario'), ('truck', 'Camión'), ('trailer', 'Acoplado'), ('other', 'Otro')], default='car', max_length=10, verbose_name='Tipo de vehículo')),
                ('plate', models.CharField(max_length=20, verbose_name='Patente')),
                ('make_model', models.CharField(max_length=150, verbose_name='Marca y modelo')),
                ('driver_name', models.CharField(max_length=200, verbose_name='Nombre y apellido del conductor')),
                ('driver_document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Pasaporte'), ('ID_CARD', 'Cédula de identidad'), ('OTHER', 'Otro')], default='DNI', max_length=10, verbose_name='Tipo de documento del conductor')),
                ('driver_document_number', models.CharField(max_length=40, verbose_name='Documento del conductor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del vehículo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='events.artworkprovider')),
            ],
            options={
                'verbose_name': 'Vehículo de proveedor de obra',
                'verbose_name_plural': 'Vehículos de proveedores de obra',
                'ordering': ['plate'],
            },
        ),
        migrations.AddField(
            model_name='artworkprovider',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_providers', to='events.artwork'),
        ),
        migrations.AddField(
            model_name='artworkprovider',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtworkLogisticsPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Pasaporte'), ('ID_CARD', 'Cédula de identidad'), ('OTHER', 'Otro')], default='DNI', max_length=10, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=40, verbose_name='Número de documento')),
                ('early_entry', models.BooleanField(default=False, verbose_name='Participa del ingreso anticipado')),
                ('early_entry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso anticipado')),
                ('dismantling', models.BooleanField(default=False, verbose_name='Participa del desarme')),
                ('dismantling_date', models.DateField(blank=True, null=True, verbose_name='Fecha de desarme y salida')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_people', to='events.artwork')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona de logística de obra',
                'verbose_name_plural': 'Personas de logística de obra',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkGrantItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=events.models.private_art_storage, upload_to='art/grants')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.artworkgrantitem')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de ítem de beca',
                'verbose_name_plural': 'Imágenes de ítems de beca',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkout_team_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_checkout_artworks', to='events.artworklogisticsperson', verbose_name='Responsable del equipo de la obra'),
        ),
        migrations.AddConstraint(
            model_name='artworkprovidervehicle',
            constraint=models.UniqueConstraint(fields=('provider', 'plate'), name='unique_artwork_provider_plate'),
        ),
        migrations.AddConstraint(
            model_name='artworklogisticsperson',
            constraint=models.UniqueConstraint(fields=('artwork', 'document_type', 'document_number'), name='unique_artwork_logistics_document'),
        ),
    ]
