# Generated by Django 4.2.15 on 2026-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_extend_art_logistics_and_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkprovider',
            name='for_entry',
            field=models.BooleanField(default=True, verbose_name='Se usa para el ingreso anticipado'),
        ),
        migrations.AddField(
            model_name='artworkprovider',
            name='for_exit',
            field=models.BooleanField(default=True, verbose_name='Se usa para el desarme y salida'),
        ),
        migrations.AddConstraint(
            model_name='artworkprovider',
            constraint=models.CheckConstraint(check=models.Q(('for_entry', True), ('for_exit', True), _connector='OR'), name='art_provider_has_operation'),
        ),
    ]
