# Generated by Django 4.2.15 on 2026-08-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_artworkprovider_for_entry_artworkprovider_for_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkprovider',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida'),
        ),
        migrations.AlterField(
            model_name='artworkprovider',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de ingreso'),
        ),
    ]
