# Generated by Django 4.2.15 on 2026-08-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0048_merge_art_and_event_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter',
            field=models.FileField(blank=True, storage=events.models.private_art_storage, upload_to='art/understanding_letters', verbose_name='Carta de entendimiento digital'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_custodian',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de la carta física'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_notes',
            field=models.TextField(blank=True, verbose_name='Ubicación o comentarios sobre la carta física'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_received',
            field=models.BooleanField(default=False, verbose_name='Carta física recibida'),
        ),
        migrations.CreateModel(
            name='ArtworkCheckoutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=events.models.private_art_storage, upload_to='art/checkout')),
                ('category', models.CharField(choices=[('dirt', 'M.U.G.R.E.'), ('environmental_damage', 'Daño ambiental'), ('artwork_parts', 'Partes de la obra'), ('burn_remains', 'Restos de quema'), ('cleanup', 'Limpieza y estado final'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('caption', models.TextField(blank=True, verbose_name='Detalle')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_photos', to='events.artwork')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de checkout de obra',
                'verbose_name_plural': 'Fotos de checkout de obras',
                'ordering': ['created_at'],
            },
        ),
    ]
