# Generated by Django 4.2.15 on 2026-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_artwork_understanding_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='understanding_letter_digital_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de carta digital'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='understanding_letter_digital_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de carta digital'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='understanding_letter_physical_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de carta física'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='understanding_letter_physical_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de carta física'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_waiver',
            field=models.BooleanField(default=False, help_text='Autoriza no entregarla previamente en CABA; igualmente debe entregarse en el evento antes de empezar a construir.', verbose_name='Excepción de entrega previa por distancia a CABA'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_waiver_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de la excepción de carta física'),
        ),
    ]
