# Generated by Django 4.2.15 on 2026-08-21 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0050_artprogram_understanding_letter_digital_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='checkin_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de llegada de la obra al evento'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkin_art_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in realizado con Arte'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkin_art_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_checkins', to=settings.AUTH_USER_MODEL, verbose_name='Check-in registrado por'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkin_placed',
            field=models.BooleanField(default=False, verbose_name='La obra quedó ubicada'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkin_placement_change_notes',
            field=models.TextField(blank=True, verbose_name='Cambio de placement y motivo'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkin_placement_changed',
            field=models.BooleanField(default=False, verbose_name='El placement original cambió'),
        ),
    ]
