# Generated by Django 4.2.15 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_artwork_checkin_arrived_at_artwork_checkin_art_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkgrantitem',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Comentarios de la revisión'),
        ),
        migrations.AddField(
            model_name='artworkgrantitem',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Revisión del ítem'),
        ),
    ]
