# Generated by Django 4.2.15 on 2026-08-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0052_artworkgrantitem_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='safety_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_responsible_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de seguridad'),
        ),
    ]
