# Generated by Django 4.2.15 on 2026-09-20

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_artwork_safety_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='public_description_max_length',
            field=models.PositiveIntegerField(
                default=200,
                validators=[MinValueValidator(1), MaxValueValidator(500)],
                verbose_name='Máximo de caracteres de la descripción del desplegable',
            ),
        ),
        migrations.AddField(
            model_name='artwork',
            name='uses_sound',
            field=models.BooleanField(default=False, verbose_name='La obra utiliza sonido amplificado'),
        ),
    ]
