# Generated by Django 4.2.15 on 2026-09-24 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0055_move_art_to_art_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['tipo__nombre', 'nombre'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='grupomiembro',
            options={'ordering': ['-ingreso_anticipado', '-late_checkout', 'user__email'], 'verbose_name': 'Miembro de equipo', 'verbose_name_plural': 'Miembros de equipo'},
        ),
        migrations.AlterModelOptions(
            name='grupotipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de equipo', 'verbose_name_plural': 'Tipos de equipo'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='event',
            field=models.ForeignKey(help_text='Evento al que pertenece el equipo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='events.event'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(help_text='Usuario responsable del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(help_text='Nombre del equipo', max_length=255),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de equipo', on_delete=django.db.models.deletion.RESTRICT, related_name='grupos', to='events.grupotipo'),
        ),
        migrations.AlterField(
            model_name='grupomiembro',
            name='grupo',
            field=models.ForeignKey(help_text='Equipo al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='events.grupo'),
        ),
        migrations.AlterField(
            model_name='grupomiembro',
            name='user',
            field=models.ForeignKey(help_text='Usuario miembro del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_miembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupotipo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el tipo de equipo está activo'),
        ),
        migrations.AlterField(
            model_name='grupotipo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del tipo de equipo', null=True),
        ),
        migrations.AlterField(
            model_name='grupotipo',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de equipo (ej: ARTE, CAMP, CAOS)', max_length=100, unique=True),
        ),
    ]
