# Generated by Django 4.2.15 on 2026-09-23 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def new_status(status, checkout_completed, checkout_verified_at):
    if status in ('accepted', 'installed'):
        if checkout_verified_at:
            return 'verified'
        return 'checkout' if checkout_completed else 'active'
    return {
        'draft': 'pending', 'submitted': 'pending', 'changes': 'pending',
        'completed': 'verified', 'cancelled': 'rejected',
    }.get(status, status)


def forwards(apps, schema_editor):
    Artwork = apps.get_model('art', 'Artwork')
    for artwork in Artwork.objects.only('status', 'checkout_completed', 'checkout_verified_at'):
        status = new_status(artwork.status, artwork.checkout_completed, artwork.checkout_verified_at)
        if status != artwork.status:
            Artwork.objects.filter(pk=artwork.pk).update(status=status)


def backwards(apps, schema_editor):
    Artwork = apps.get_model('art', 'Artwork')
    for old, new in (('draft', 'pending'), ('accepted', 'active'), ('installed', 'checkout'), ('completed', 'verified')):
        Artwork.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0003_delete_empty_artwork_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cambio de estado'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Estado cambiado por'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='Mensaje de ESTAFA al equipo de la obra'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Inscripción pendiente'), ('active', 'Inscripción activa'), ('rejected', 'Rechazada'), ('checkout', 'Checkout enviado'), ('verified', 'Checkout verificado')], default='pending', max_length=12, verbose_name='Estado de la obra'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
