# Generated by Django 4.2.15 on 2026-09-23 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artwork_status_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Instalación de Arte', 'verbose_name_plural': 'Instalaciones de Arte'},
        ),
        migrations.AlterModelOptions(
            name='artworkcheckoutphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'Foto de checkout de instalación', 'verbose_name_plural': 'Fotos de checkout de instalaciones'},
        ),
        migrations.AlterModelOptions(
            name='artworklogisticsperson',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Persona de logística de instalación', 'verbose_name_plural': 'Personas de logística de instalación'},
        ),
        migrations.AlterModelOptions(
            name='artworkphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'Foto de instalación', 'verbose_name_plural': 'Fotos de instalaciones'},
        ),
        migrations.AlterModelOptions(
            name='artworkprovider',
            options={'ordering': ['company_name'], 'verbose_name': 'Proveedor de instalación', 'verbose_name_plural': 'Proveedores de instalación'},
        ),
        migrations.AlterModelOptions(
            name='artworkprovidervehicle',
            options={'ordering': ['plate'], 'verbose_name': 'Vehículo de proveedor de instalación', 'verbose_name_plural': 'Vehículos de proveedores de instalación'},
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='early_entry_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupos de ingreso anticipado por instalación'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='late_checkout_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupos de late checkout por instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkin_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de llegada de la instalación al evento'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkin_placed',
            field=models.BooleanField(default=False, verbose_name='La instalación quedó ubicada'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkout_team_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_checkout_artworks', to='art.artworklogisticsperson', verbose_name='Responsable del equipo de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='grant_justification',
            field=models.TextField(blank=True, verbose_name='Por qué la beca hace posible la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='grant_report',
            field=models.TextField(blank=True, verbose_name='Rendición y resultado de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='kind',
            field=models.CharField(choices=[('planned', 'Instalación inscripta'), ('popup', 'Instalación espontánea (popup)')], default='planned', max_length=10, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='Mensaje de ESTAFA al equipo de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Inscripción pendiente'), ('active', 'Inscripción activa'), ('rejected', 'Rechazada'), ('checkout', 'Checkout enviado'), ('verified', 'Checkout verificado')], default='pending', max_length=12, verbose_name='Estado de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='uses_fire',
            field=models.BooleanField(default=False, verbose_name='La instalación utiliza fuego'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='uses_sound',
            field=models.BooleanField(default=False, verbose_name='La instalación utiliza sonido amplificado'),
        ),
        migrations.AlterField(
            model_name='artworkcheckoutphoto',
            name='category',
            field=models.CharField(choices=[('dirt', 'M.U.G.R.E.'), ('environmental_damage', 'Daño ambiental'), ('artwork_parts', 'Partes de la instalación'), ('burn_remains', 'Restos de quema'), ('cleanup', 'Limpieza y estado final'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='artworkphoto',
            name='stage',
            field=models.CharField(choices=[('proposal', 'Propuesta'), ('process', 'Proceso'), ('final', 'Instalación terminada'), ('grant', 'Rendición de beca')], default='process', max_length=10, verbose_name='Etapa'),
        ),
    ]
