# Generated by Django 4.2.15 on 2026-09-24 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0056_equipo_labels'),
        ('art', '0008_artwork_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworklogisticsperson',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='artworklogisticsperson',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkout_team_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_checkout_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Pueden editar'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='operations_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork', to='events.grupo', verbose_name='Equipo'),
        ),
        migrations.DeleteModel(
            name='ArtworkInvitation',
        ),
        migrations.DeleteModel(
            name='ArtworkLogisticsPerson',
        ),
    ]
