# Generated by Django 4.2.15 on 2026-09-24 01:55

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_artwork_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de declaración física'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de declaración física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Inscripción pendiente'), ('active', 'Inscripción aprobada'), ('rejected', 'Rechazada'), ('checkout', 'Checkout enviado'), ('verified', 'Checkout verificado')], default='pending', max_length=12, verbose_name='Estado de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter',
            field=models.FileField(blank=True, storage=art.models.private_art_storage, upload_to='art/understanding_letters', verbose_name='Declaración de entendimiento digital'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_custodian',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de la declaración física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_notes',
            field=models.TextField(blank=True, verbose_name='Ubicación o comentarios sobre la declaración física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_received',
            field=models.BooleanField(default=False, verbose_name='Declaración física recibida'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_waiver_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de la excepción de declaración física'),
        ),
    ]
