# Generated by Django 4.2.15 on 2026-09-24 02:31

import art.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_proposal_photos_to_files(apps, schema_editor):
    """Las fotos de propuesta pasan a ser archivos de Detalles; el archivo guardado no se mueve."""
    ArtworkPhoto = apps.get_model('art', 'ArtworkPhoto')
    ArtworkFile = apps.get_model('art', 'ArtworkFile')
    for photo in ArtworkPhoto.objects.filter(stage='proposal'):
        ArtworkFile.objects.create(
            artwork_id=photo.artwork_id,
            file=photo.image.name,
            name=photo.caption[:255] or photo.image.name.rsplit('/', 1)[-1],
            uploaded_by_id=photo.uploaded_by_id,
        )
        photo.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0009_artwork_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='gallery_deadline',
            field=models.DateTimeField(blank=True, help_text='La galería se habilita cuando empieza el evento. Sin fecha de cierre, cierra cuando termina.', null=True, verbose_name='Cierre de galería'),
        ),
        migrations.AddField(
            model_name='artprogram',
            name='logistics_opens',
            field=models.DateTimeField(blank=True, help_text='Mientras esté vacía, el paso queda cerrado y los equipos ven “Te avisamos cuando se habilite”. La fecha nunca se les muestra antes de que se habilite.', null=True, verbose_name='Apertura de ingreso anticipado y proveedores'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='burn_company',
            field=models.CharField(blank=True, choices=[('alone', 'Sola'), ('shared', 'Junto con otras instalaciones'), ('either', 'Me da igual')], max_length=10, verbose_name='¿La querés quemar sola o junto con otras instalaciones?'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='burn_preferred_time',
            field=models.CharField(blank=True, help_text='Por ejemplo: sábado a la noche, después de la quema principal.', max_length=200, verbose_name='¿Cuándo preferís quemarla?'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='burns',
            field=models.BooleanField(default=False, verbose_name='La instalación se quema'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='files_url',
            field=models.URLField(blank=True, help_text='Una carpeta con más material, por ejemplo de Google Drive o Dropbox.', max_length=500, verbose_name='Link a más archivos'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='understanding_letter_physical_received_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recepción de la copia física'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de entrega de la copia física'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de entrega de la copia física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_custodian',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quién tiene la copia física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_notes',
            field=models.TextField(blank=True, verbose_name='Ubicación o comentarios sobre la copia física'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_received',
            field=models.BooleanField(default=False, verbose_name='Copia física recibida'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter_physical_waiver_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de la excepción de la copia física'),
        ),
        migrations.CreateModel(
            name='ArtworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=art.models.private_art_storage, upload_to='art/files', verbose_name='Archivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='art.artwork')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de instalación',
                'verbose_name_plural': 'Archivos de instalaciones',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(move_proposal_photos_to_files, migrations.RunPython.noop),
    ]
