# Generated by Django 4.2.15 on 2026-09-24 02:43

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_artwork_files_and_step_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apertura de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Inscripción pendiente'), ('active', 'Inscripción aprobada'), ('rejected', 'Rechazada'), ('checkout', 'Checkout enviado'), ('verified', 'Checkout verificado')], default='pending', max_length=12, verbose_name='Estado de la instalación'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='understanding_letter',
            field=models.FileField(blank=True, storage=art.models.private_art_storage, upload_to='art/understanding_letters', verbose_name='Declaración de entendimiento digital'),
        ),
    ]
