# Generated by Django 4.2.15 on 2026-09-24 02:56

import art.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_equipo_labels'),
        ('art', '0011_estafa_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artprogram',
            name='understanding_letter_digital_opens',
        ),
        migrations.RemoveField(
            model_name='artprogram',
            name='understanding_letter_physical_opens',
        ),
        migrations.AddField(
            model_name='artprogram',
            name='grant_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo se puede pedir beca. Vacía: desde ya.', null=True, verbose_name='Apertura de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='checkout_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para enviar el checkout. Vacía: cuando termina el evento.', null=True, verbose_name='Cierre de checkout'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='checkout_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo los equipos pueden enviar el checkout. Vacía: cuando empieza el evento.', null=True, verbose_name='Apertura de checkout'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='early_entry_from',
            field=models.DateTimeField(blank=True, help_text='Se copia al equipo de cada instalación cuando se crea. Cambiarlo no modifica los equipos que ya existen.', null=True, verbose_name='Ingreso anticipado desde'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='early_entry_slots',
            field=models.PositiveIntegerField(default=0, help_text='Se copia al equipo de cada instalación cuando se crea. Cambiarlo no modifica los equipos que ya existen.', verbose_name='Cupos de ingreso anticipado por instalación'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_program', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grant_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para pedir beca y cargar el presupuesto. Vacía: sin cierre.', null=True, verbose_name='Cierre de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grant_report_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para rendir una beca aprobada. Vacía: sin cierre.', null=True, verbose_name='Cierre de rendición de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grants_enabled',
            field=models.BooleanField(default=False, help_text='Muestra el paso de beca a los equipos.', verbose_name='Becas habilitadas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='guide_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar el título y el texto para el público y la ubicación preferida. Vacía: cierra cuando empieza el evento.', null=True, verbose_name='Cierre de desplegable y placement'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='is_current',
            field=models.BooleanField(default=False, help_text='La única convocatoria que acepta instalaciones nuevas y que los equipos pueden editar. Las demás quedan como histórico, en modo consulta.', verbose_name='Convocatoria anual vigente'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='late_checkout_slots',
            field=models.PositiveIntegerField(default=0, help_text='Se copia al equipo de cada instalación cuando se crea. Cambiarlo no modifica los equipos que ya existen.', verbose_name='Cupos de late checkout por instalación'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='late_checkout_until',
            field=models.DateTimeField(blank=True, help_text='Se copia al equipo de cada instalación cuando se crea. Cambiarlo no modifica los equipos que ya existen.', null=True, verbose_name='Late checkout hasta'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='logistics_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para cargar ingreso anticipado, late checkout, proveedores y vehículos. Vacía: cierra cuando empieza el evento.', null=True, verbose_name='Cierre de logística'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='logistics_opens',
            field=models.DateTimeField(blank=True, help_text='Mientras esté vacía, el paso queda cerrado y los equipos ven “Te avisamos cuando se habilite”. La fecha nunca se les muestra antes de que se habilite.', null=True, verbose_name='Apertura de logística'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='proposal_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar los detalles de la instalación: descripción, dimensiones, materiales y seguridad. Puede ser posterior al cierre de inscripción. Vacía: cierra cuando empieza el evento.', null=True, verbose_name='Cierre de detalles'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_closes',
            field=models.DateTimeField(blank=True, help_text='Hasta cuándo se pueden inscribir instalaciones nuevas. Las ya inscriptas se siguen completando según las fechas de cada paso. Vacía: sin cierre.', null=True, verbose_name='Cierre de inscripción'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo se pueden inscribir instalaciones nuevas (botón «Nueva instalación»). Vacía: desde ya.', null=True, verbose_name='Apertura de inscripción'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='reminder_days',
            field=models.JSONField(blank=True, default=art.models.default_art_reminder_days, help_text='Cuántos días antes de cada cierre se manda un recordatorio, por ejemplo [7, 3, 1]. Una lista vacía los desactiva.', verbose_name='Días de anticipación para recordatorios'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para subir la declaración firmada. Vacía: cierra cuando empieza el evento.', null=True, verbose_name='Cierre de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para entregar la copia en papel. Vacía: cuando empieza el evento.', null=True, verbose_name='Cierre de entrega de la copia física'),
        ),
    ]
