# Generated by Django 4.2.15 on 2026-09-24 03:10

from django.db import migrations, models


# Hasta 0012, un cierre vacío caía en el evento (lo previo cuando empieza; galería y checkout cuando
# termina), la galería y el checkout abrían cuando empieza el evento y la inscripción y las becas
# abrían desde ya. Ahora vacía significa sin habilitar o sin cierre: se completan los programas
# existentes con esas fechas para que no cambie lo que ven los equipos.
FROM_EVENT_START = (
    'proposal_deadline', 'guide_deadline', 'logistics_deadline',
    'understanding_letter_digital_deadline', 'understanding_letter_physical_deadline',
    'gallery_opens', 'checkout_opens',
)
FROM_EVENT_END = ('gallery_deadline', 'checkout_deadline')
# Apertura: su cierre, para no quedar después de él.
FROM_CREATION = {'registration_opens': 'registration_closes', 'grant_opens': 'grant_deadline'}


def fill_from_event(apps, schema_editor):
    ArtProgram = apps.get_model('art', 'ArtProgram')
    for program in ArtProgram.objects.select_related('event'):
        defaults = {name: program.event.start for name in FROM_EVENT_START}
        defaults.update({name: program.event.end for name in FROM_EVENT_END})
        defaults.update({
            name: min(filter(None, (program.created_at, getattr(program, closes))))
            for name, closes in FROM_CREATION.items()
        })
        for name, value in defaults.items():
            if getattr(program, name) is None:
                setattr(program, name, value)
        program.save(update_fields=list(defaults))


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_program_help_and_grant_opens'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='gallery_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo los equipos pueden subir fotos del armado y de la instalación terminada. Vacía: el paso no se habilita.', null=True, verbose_name='Apertura de galería'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='checkout_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para enviar el checkout. Vacía: no cierra.', null=True, verbose_name='Cierre de checkout'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='checkout_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo los equipos pueden enviar el checkout. Vacía: el paso no se habilita.', null=True, verbose_name='Apertura de checkout'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='gallery_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para subir fotos a la galería. Vacía: no cierra.', null=True, verbose_name='Cierre de galería'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grant_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para pedir beca y cargar el presupuesto. Vacía: no cierra.', null=True, verbose_name='Cierre de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grant_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo se puede pedir beca. Vacía: el paso no se habilita.', null=True, verbose_name='Apertura de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='grant_report_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para rendir una beca aprobada. Vacía: no cierra.', null=True, verbose_name='Cierre de rendición de becas'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='guide_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar el título y el texto para el público y la ubicación preferida. Vacía: no cierra.', null=True, verbose_name='Cierre de desplegable y placement'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='logistics_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para cargar ingreso anticipado, late checkout, proveedores y vehículos. Vacía: no cierra.', null=True, verbose_name='Cierre de logística'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='proposal_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar los detalles de la instalación: descripción, dimensiones, materiales y seguridad. Puede ser posterior al cierre de inscripción. Vacía: no cierra.', null=True, verbose_name='Cierre de detalles'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_closes',
            field=models.DateTimeField(blank=True, help_text='Hasta cuándo se pueden inscribir instalaciones nuevas. Las ya inscriptas se siguen completando según las fechas de cada paso. Vacía: no cierra.', null=True, verbose_name='Cierre de inscripción'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo se pueden inscribir instalaciones nuevas (botón «Nueva instalación»). Vacía: la inscripción no se habilita.', null=True, verbose_name='Apertura de inscripción'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_digital_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para subir la declaración firmada. Vacía: no cierra.', null=True, verbose_name='Cierre de declaración digital'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='understanding_letter_physical_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para entregar la copia en papel. Vacía: no cierra.', null=True, verbose_name='Cierre de entrega de la copia física'),
        ),
        migrations.RunPython(fill_from_event, migrations.RunPython.noop),
    ]
