# Generated by Django 4.2.15 on 2026-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_program_dates_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='checkout_staff_notes',
            field=models.TextField(blank=True, help_text='Sólo los ve ESTAFA: el equipo de la instalación no los ve.', verbose_name='Comentarios de ESTAFA'),
        ),
    ]
