# Generated by Django 4.2.15 on 2026-10-08 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0014_checkout_staff_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Propuesta de Arte', 'verbose_name_plural': 'Propuestas de Arte'},
        ),
        migrations.AlterModelOptions(
            name='artworkfile',
            options={'ordering': ['created_at'], 'verbose_name': 'Archivo de propuesta de Arte', 'verbose_name_plural': 'Archivos de propuestas de Arte'},
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='early_entry_from',
            field=models.DateTimeField(blank=True, help_text='Se copia al equipo de cada propuesta de Arte cuando se crea. Cambiarlo no modifica los equipos que ya existen.', null=True, verbose_name='Ingreso anticipado desde'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='early_entry_slots',
            field=models.PositiveIntegerField(default=0, help_text='Se copia al equipo de cada propuesta de Arte cuando se crea. Cambiarlo no modifica los equipos que ya existen.', verbose_name='Cupos de ingreso anticipado por propuesta de Arte'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='guide_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar el título y el texto para el público y la ubicación preferida. Vacía: no cierra.', null=True, verbose_name='Cierre de folleto y placement'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='is_current',
            field=models.BooleanField(default=False, help_text='La única convocatoria que acepta propuestas de Arte nuevas y que los equipos pueden editar. Las demás quedan como histórico, en modo consulta.', verbose_name='Convocatoria anual vigente'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='late_checkout_slots',
            field=models.PositiveIntegerField(default=0, help_text='Se copia al equipo de cada propuesta de Arte cuando se crea. Cambiarlo no modifica los equipos que ya existen.', verbose_name='Cupos de late checkout por propuesta de Arte'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='late_checkout_until',
            field=models.DateTimeField(blank=True, help_text='Se copia al equipo de cada propuesta de Arte cuando se crea. Cambiarlo no modifica los equipos que ya existen.', null=True, verbose_name='Late checkout hasta'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='proposal_deadline',
            field=models.DateTimeField(blank=True, help_text='Último momento para editar los detalles de la propuesta: descripción, dimensiones, materiales y seguridad. Puede ser posterior al cierre de inscripción. Vacía: no cierra.', null=True, verbose_name='Cierre de detalles'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='public_description_max_length',
            field=models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Máximo de caracteres de la descripción del folleto'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_closes',
            field=models.DateTimeField(blank=True, help_text='Hasta cuándo se pueden inscribir propuestas de Arte nuevas. Las ya inscriptas se siguen completando según las fechas de cada paso. Vacía: no cierra.', null=True, verbose_name='Cierre de inscripción'),
        ),
        migrations.AlterField(
            model_name='artprogram',
            name='registration_opens',
            field=models.DateTimeField(blank=True, help_text='Desde cuándo se pueden inscribir propuestas de Arte nuevas (botón «Nueva propuesta de Arte»). Vacía: la inscripción no se habilita.', null=True, verbose_name='Apertura de inscripción'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='burn_company',
            field=models.CharField(blank=True, choices=[('alone', 'Sola'), ('shared', 'Junto con otras obras'), ('either', 'Me da igual')], max_length=10, verbose_name='¿Preferirías quemarla sola o junto con otras obras?'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkout_staff_notes',
            field=models.TextField(blank=True, help_text='Sólo los ve ESTAFA: el equipo de la propuesta no los ve.', verbose_name='Comentarios de ESTAFA'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='checkout_team_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_checkout_artworks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del equipo de la propuesta'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='kind',
            field=models.CharField(choices=[('planned', 'Propuesta inscripta'), ('popup', 'Propuesta espontánea (popup)')], default='planned', max_length=10, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='public_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción para el folleto'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='public_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Título para el folleto'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='review_feedback',
            field=models.TextField(blank=True, verbose_name='Mensaje de ESTAFA al equipo de la propuesta'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('pending', 'Inscripción pendiente'), ('active', 'Inscripción aprobada'), ('rejected', 'Rechazada'), ('checkout', 'Checkout enviado'), ('verified', 'Checkout verificado')], default='pending', max_length=12, verbose_name='Estado de la propuesta'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre de la propuesta'),
        ),
    ]
