# Generated by Django 4.2.15 on 2026-10-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0016_sound_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkcheckoutphoto',
            name='category',
        ),
    ]
