# Generated by Django 4.2.15 on 2026-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_remove_checkout_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='image',
            field=models.ImageField(blank=True, help_text='Se muestra arriba de todo en Mi Fuego → Arte mientras la convocatoria está vigente. Ideal: apaisada, 1600 × 400 px.', upload_to='art/programs', verbose_name='Imagen'),
        ),
    ]
