# Generated by Django 4.2.15 on 2026-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0018_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='share_description',
            field=models.TextField(blank=True, help_text='Lo que se lee al compartir un link de Mi Fuego → Arte (WhatsApp, redes). Vacío: se usa la descripción del evento. Se muestran hasta 200 caracteres.', verbose_name='Texto para compartir'),
        ),
    ]
