# Generated by Django 4.2.15 on 2026-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0019_program_share_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprogram',
            name='share_title',
            field=models.CharField(blank=True, help_text='El título al compartir un link de Mi Fuego → Arte. Vacío: se usa el título del evento.', max_length=120, verbose_name='Título para compartir'),
        ),
    ]
