from django.urls import path

from .views import (
    complete_profile,
    stop_impersonation_view,
    verification_congrats,
    profile_congrats,
    my_fire_view,
    my_ticket_view,
    transferable_tickets_view,
    volunteering,
    my_orders_view,
    mis_logros_view,
    logros_mark_celebration_shown,
    admin_logros_view,
    admin_logros_assign_view,
    la_sede_view,
    propose_event_view,
    my_event_requests_view,
    my_events_view,
    event_admin_view,
    puerta_admin_view,
    caja_config_view,
    caja_config_ajax,
    scanner_events_view,
    caja_events_view,
    bonus_report_view,
    caja_view,
    profile_view,
    send_phone_code_ajax,
    verify_phone_code_ajax,
    my_tickets_ajax,
    update_ticket_restriccion,
    download_ticket_pdf,
    roles_management_view,
    event_management_view,
    ticket_types_management_view,
    ticket_types_ajax,
    accept_terms_ajax,
    mis_grupos_view,
    grupo_manage_view,
    grupo_toggle_ajax,
)
from events.art_views import (
    art_admin_dashboard, art_admin_export, art_dashboard, art_invitation_accept,
    artwork_provider_delete, artwork_provider_edit, artwork_vehicle_delete,
    artwork_vehicle_edit,
    artwork_create, artwork_edit, artwork_photo_delete, artwork_photo_upload,
    artwork_review, grant_item_create, grant_item_delete, grant_item_edit,
    grant_item_photo_delete, grant_report_submit, grant_submit,
    logistics_person_delete, logistics_person_edit,
)

urlpatterns = [
    # Profile related paths
    path("complete-profile/", complete_profile, name="complete_profile"),
    path("verification-congrats/", verification_congrats, name="verification_congrats"),
    path("profile-congrats/", profile_congrats, name="profile_congrats"),
    path("perfil/", profile_view, name="profile"),
    path("perfil/send-phone-code/", send_phone_code_ajax, name="send_phone_code_ajax"),
    path("perfil/verify-phone-code/", verify_phone_code_ajax, name="verify_phone_code_ajax"),
    path("", my_fire_view, name="mi_fuego"),
    path("impersonation/stop/", stop_impersonation_view, name="stop_impersonation"),
    # Specific paths (must come before generic slug pattern)
    path("mis-bonos/eventos-anteriores/", my_ticket_view, {"event_slug": "eventos-anteriores"}, name="my_ticket_past"),
    path("mis-bonos/ordenes/", my_orders_view, name="my_orders"),
    path("mis-bonos/logros/", mis_logros_view, name="mis_logros"),
    path("mis-bonos/logros/celebracion-vista/", logros_mark_celebration_shown, name="logros_mark_celebration_shown"),
    path("admin-logros/", admin_logros_view, name="admin_logros"),
    path("admin-logros/asignar/", admin_logros_assign_view, name="admin_logros_assign"),
    path("la-sede/", la_sede_view, name="la_sede"),
    path("la-sede/proponer-evento/", propose_event_view, name="propose_event"),
    path("la-sede/mis-propuestas/", my_event_requests_view, name="my_event_requests"),
    path("arte/", art_dashboard, name="art_dashboard"),
    path("arte/<slug:event_slug>/nueva/", artwork_create, name="artwork_create"),
    path("arte/obra/<int:artwork_id>/", artwork_edit, name="artwork_edit"),
    path("arte/obra/<int:artwork_id>/beca/<str:phase>/nuevo/", grant_item_create, name="grant_item_create"),
    path("arte/obra/<int:artwork_id>/beca/item/<int:item_id>/", grant_item_edit, name="grant_item_edit"),
    path("arte/obra/<int:artwork_id>/beca/item/<int:item_id>/eliminar/", grant_item_delete, name="grant_item_delete"),
    path("arte/obra/<int:artwork_id>/beca/item/<int:item_id>/imagen/<int:photo_id>/eliminar/", grant_item_photo_delete, name="grant_item_photo_delete"),
    path("arte/obra/<int:artwork_id>/beca/enviar/", grant_submit, name="grant_submit"),
    path("arte/obra/<int:artwork_id>/rendicion/enviar/", grant_report_submit, name="grant_report_submit"),
    path("arte/obra/<int:artwork_id>/fotos/subir/", artwork_photo_upload, name="artwork_photo_upload"),
    path("arte/obra/<int:artwork_id>/fotos/<int:photo_id>/eliminar/", artwork_photo_delete, name="artwork_photo_delete"),
    path("arte/obra/<int:artwork_id>/logistica/personas/nueva/", logistics_person_edit, name="logistics_person_create"),
    path("arte/obra/<int:artwork_id>/logistica/personas/<int:person_id>/", logistics_person_edit, name="logistics_person_edit"),
    path("arte/obra/<int:artwork_id>/logistica/personas/<int:person_id>/eliminar/", logistics_person_delete, name="logistics_person_delete"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/nuevo/", artwork_provider_edit, name="artwork_provider_create"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/<int:provider_id>/", artwork_provider_edit, name="artwork_provider_edit"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/<int:provider_id>/eliminar/", artwork_provider_delete, name="artwork_provider_delete"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/<int:provider_id>/vehiculos/nuevo/", artwork_vehicle_edit, name="artwork_vehicle_create"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/<int:provider_id>/vehiculos/<int:vehicle_id>/", artwork_vehicle_edit, name="artwork_vehicle_edit"),
    path("arte/obra/<int:artwork_id>/logistica/proveedores/<int:provider_id>/vehiculos/<int:vehicle_id>/eliminar/", artwork_vehicle_delete, name="artwork_vehicle_delete"),
    path("arte/invitacion/<uuid:token>/aceptar/", art_invitation_accept, name="art_invitation_accept"),
    path("mis-eventos/<slug:event_slug>/arte/", art_admin_dashboard, name="art_admin_dashboard"),
    path("mis-eventos/<slug:event_slug>/arte/exportar/", art_admin_export, name="art_admin_export"),
    path("mis-eventos/<slug:event_slug>/arte/<int:artwork_id>/", artwork_review, name="artwork_review"),
    path("mis-eventos/", my_events_view, name="my_events"),
    path("mis-eventos/<slug:event_slug>/", event_admin_view, name="event_admin"),
    path("mis-eventos/<slug:event_slug>/configuracion/", event_management_view, name="event_management"),
    path("mis-eventos/<slug:event_slug>/tipos-entradas/", ticket_types_management_view, name="ticket_types_management"),
    path("mis-eventos/<slug:event_slug>/tipos-entradas/ajax/", ticket_types_ajax, name="ticket_types_ajax"),
    path("mis-eventos/<slug:event_slug>/roles/", roles_management_view, name="roles_management"),
    path("mis-eventos/<slug:event_slug>/puerta/", puerta_admin_view, name="puerta_admin"),
    path("mis-eventos/<slug:event_slug>/reporte-bonos/", bonus_report_view, name="bonus_report"),
    path("mis-eventos/<slug:event_slug>/caja/", caja_view, name="caja"),
    path("mis-eventos/<slug:event_slug>/configuracion-caja/", caja_config_view, name="caja_config"),
    path("mis-eventos/<slug:event_slug>/configuracion-caja/ajax/", caja_config_ajax, name="caja_config_ajax"),
    path("scanner/", scanner_events_view, name="scanner_events"),
    path("cajas/", caja_events_view, name="caja_events"),
    # Event-specific paths
    path("mis-bonos/<slug:event_slug>/volunteering/", volunteering, name="volunteering"),
    path("mis-bonos/<slug:event_slug>/grupos/", mis_grupos_view, name="mis_grupos"),
    path("mis-bonos/<slug:event_slug>/grupos/<int:grupo_id>/", grupo_manage_view, name="grupo_manage"),
    path("mis-bonos/<slug:event_slug>/grupos/<int:grupo_id>/ajax/", grupo_toggle_ajax, name="grupo_toggle_ajax"),
    path("mis-bonos/<slug:event_slug>/bonos-transferibles/", transferable_tickets_view, name="transferable_tickets"),
    # Event-specific ticket views (after specific paths)
    path("mis-bonos/<slug:event_slug>/", my_ticket_view, name="my_ticket_event"),
    # AJAX endpoint for auto-refresh
    path("mis-bonos/<slug:event_slug>/ajax/", my_tickets_ajax, name="my_tickets_ajax"),
    # AJAX endpoint for updating ticket restriction
    path("ticket/<str:ticket_key>/update-restriccion/", update_ticket_restriccion, name="update_ticket_restriccion"),
    # Download ticket PDF
    path("ticket/<str:ticket_key>/download-pdf/", download_ticket_pdf, name="download_ticket_pdf"),
    # AJAX endpoint for accepting terms
    path("accept-terms/", accept_terms_ajax, name="accept_terms_ajax"),
    # Default redirect (no slug) - MUST BE LAST
    path("mis-bonos/", my_ticket_view, name="my_ticket"),
]
