# Generated by Django 4.2.24 on 2025-09-13 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la sección', max_length=100)),
                ('description', models.TextField(help_text='Descripción de la sección')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Sección activa')),
            ],
            options={
                'verbose_name': 'Sección del Foro',
                'verbose_name_plural': 'Secciones del Foro',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Título del hilo', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Hilo activo')),
                ('is_pinned', models.BooleanField(default=False, help_text='Hilo fijado')),
                ('is_locked', models.BooleanField(default=False, help_text='Hilo bloqueado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.forumsection')),
            ],
            options={
                'verbose_name': 'Hilo del Foro',
                'verbose_name_plural': 'Hilos del Foro',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Contenido del mensaje')),
                ('is_active', models.BooleanField(default=True, help_text='Mensaje activo')),
                ('is_edited', models.BooleanField(default=False, help_text='Mensaje editado')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Fecha de edición', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forumthread')),
            ],
            options={
                'verbose_name': 'Mensaje del Foro',
                'verbose_name_plural': 'Mensajes del Foro',
                'ordering': ['created_at'],
            },
        ),
    ]
