# Generated by Django 4.2.24 on 2025-09-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forum_username',
            field=models.CharField(blank=True, help_text='Nombre de usuario para el foro', max_length=50, null=True, unique=True),
        ),
    ]
