# Generated by Django 4.2.24 on 2025-09-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_forum_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar del usuario', null=True, upload_to='avatars/'),
        ),
    ]
