# Generated by Django 4.2.15 on 2026-05-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_sede_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(max_length=64, unique=True)),
                ('plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('tier_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('matched_via', models.CharField(blank=True, default='', max_length=16)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sede_subscriptions', to='user_profile.profile')),
            ],
            options={
                'ordering': ('-is_active', '-last_payment_date', '-created_at'),
            },
        ),
    ]
