# Generated by Django 4.2.15 on 2026-05-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_sedesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeUnmatchedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(max_length=64, unique=True)),
                ('plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('tier_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('payer_id', models.CharField(blank=True, default='', max_length=64)),
                ('payer_email', models.CharField(blank=True, default='', max_length=255)),
                ('payer_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('payer_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('document_number', models.CharField(blank=True, default='', max_length=128)),
                ('payment_method', models.CharField(blank=True, default='', max_length=64)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=dict)),
                ('unresolved_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-last_seen_at', '-updated_at'),
            },
        ),
    ]
