# Generated by Django 4.2.15 on 2026-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_sedeunmatchedsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.CharField(max_length=64, unique=True)),
                ('plan_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('subscriptions_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-is_enabled', 'plan_name', 'plan_id'),
            },
        ),
    ]
