# Generated by Django 4.2.15 on 2026-05-24 16:00

from django.db import migrations


def clear_sede_tables(apps, schema_editor):
    SedeSubscription = apps.get_model('user_profile', 'SedeSubscription')
    SedeUnmatchedSubscription = apps.get_model('user_profile', 'SedeUnmatchedSubscription')
    SedeSubscription.objects.all().delete()
    SedeUnmatchedSubscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_sedesubscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='miembro_sede',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_last_payment_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_last_payment_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_member_since',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_next_payment_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_payment_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_subscription_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_subscription_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sede_synced_at',
        ),
        migrations.RunPython(clear_sede_tables, migrations.RunPython.noop),
    ]
