# Generated by Django 4.2.15 on 2026-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_sede_subscription_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedesubscriptionplan',
            name='billing_cycle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
