# Generated by Django 4.2.15 on 2026-09-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_sedesubscription_soft_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, verbose_name='¿Cómo te dicen?'),
        ),
    ]
