# Generated by Django 3.2.9 on 2021-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='color',
            field=models.CharField(default='6633ff', max_length=6),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='emoji',
            field=models.CharField(default='🖕', max_length=1),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
