# Generated by Django 3.2.9 on 2021-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20211204_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price_with_coupon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('price__isnull', True), ('price_with_coupon__isnull', False)), models.Q(('price__isnull', False), ('price_with_coupon__isnull', True)), _connector='OR'), name='tickets_tickettype_price_or_price_with_coupon'),
        ),
    ]
