# Generated by Django 3.2.9 on 2021-12-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_tickettype_tickets_tickettype_price_or_price_with_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='ticket_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
