# Generated by Django 3.2.9 on 2021-12-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_tickettype_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donations',
            field=models.JSONField(null=True),
        ),
    ]
