# Generated by Django 3.2.9 on 2021-12-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='coupon',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='coupons',
            field=models.ManyToManyField(blank=True, null=True, to='tickets.Coupon'),
        ),
    ]
