# Generated by Django 3.2.9 on 2021-12-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20211209_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='coupons',
        ),
        migrations.AddField(
            model_name='coupon',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
            preserve_default=False,
        ),
    ]
