# Generated by Django 3.2.9 on 2021-12-11 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20211209_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='donations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
