# Generated by Django 3.2.9 on 2021-12-11 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20211211_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
