# Generated by Django 3.2.9 on 2021-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='volunteer',
            field=models.CharField(choices=[('yes', 'Quiero ser parte del voluntariado'), ('ask', 'No sé, pregúntenle'), ('no', 'No le interesa')], default='ask', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='volunteer_ranger',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='volunteer_transmutator',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='volunteer_umpalumpa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
