# Generated by Django 3.2.9 on 2021-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20211214_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donations',
        ),
        migrations.AddField(
            model_name='order',
            name='donation_art',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='donation_grant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='donation_venue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='volunteer',
            field=models.CharField(choices=[('yes', 'Quiero ser parte del voluntariado'), ('ask', 'No sé aún'), ('no', 'No me interesa')], max_length=10),
        ),
    ]
