# Generated by Django 3.2.9 on 2021-12-22 20:47

from django.db import migrations

def cross_donations(apps, schema_editor):
    Order = apps.get_model('tickets', 'Order')  
    for order in Order.objects.all():
        donation_grant = order.donation_venue
        donation_venue = order.donation_grant
        order.donation_grant = donation_grant
        order.donation_venue = donation_venue
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20211214_1910'),
    ]

    operations = [
        migrations.RunPython(cross_donations),
    ]
