# Generated by Django 3.2.9 on 2021-12-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20211222_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donation_art',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para empujar la creatividad en nuestra ciudad temporal.', max_digits=10, null=True, verbose_name='Becas de Arte'),
        ),
        migrations.AlterField(
            model_name='order',
            name='donation_grant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para mejorar el espacio donde nos encontramos todo el año.', max_digits=10, null=True, verbose_name='Becas No Tengo Un Mango (NTUM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='donation_venue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para ayudar a quienes necesitan una mano con su bono contribución.', max_digits=10, null=True, verbose_name='Donaciones a La Sede'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='volunteer',
            field=models.CharField(choices=[('ask', 'No sé aún'), ('no', 'No me interesa'), ('yes', 'Quiero ser parte del voluntariado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='volunteer_ranger',
            field=models.BooleanField(verbose_name='Rangers'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='volunteer_transmutator',
            field=models.BooleanField(verbose_name='Transmutadores'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='volunteer_umpalumpa',
            field=models.BooleanField(verbose_name='Umpa Lumpas (Armado y Desarme de la Ciudad)'),
        ),
    ]
