# Generated by Django 3.2.9 on 2023-01-02 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20211222_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=320)),
                ('phone', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('volunteer', models.CharField(choices=[('ask', 'No sé aún'), ('no', 'No me interesa'), ('yes', 'Quiero ser parte del voluntariado')], max_length=10)),
                ('volunteer_ranger', models.BooleanField(verbose_name='Rangers')),
                ('volunteer_transmutator', models.BooleanField(verbose_name='Transmutadores')),
                ('volunteer_umpalumpa', models.BooleanField(verbose_name='Umpa Lumpas (Armado y Desarme de la Ciudad)')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transferred', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
