# Generated by Django 3.2.9 on 2023-04-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230417_1627'),
        ('tickets', '0020_auto_20230109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
