# Generated by Django 3.2.9 on 2023-11-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_tickettype_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='volunteer_umpalumpa',
            field=models.BooleanField(verbose_name='CAOS (Desarme de la Ciudad)'),
        ),
        migrations.AlterField(
            model_name='tickettransfer',
            name='volunteer_umpalumpa',
            field=models.BooleanField(verbose_name='CAOS (Desarme de la Ciudad)'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='emoji',
            field=models.CharField(default='🖕', max_length=255),
        ),
    ]
