# Generated by Django 3.2.9 on 2023-11-01 02:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20231031_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donation_art',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Para empujar la creatividad en nuestra ciudad temporal.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Becas de Arte $'),
        ),
        migrations.AlterField(
            model_name='order',
            name='donation_grant',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Para ayudar a quienes necesitan una mano con su bono contribución.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Beca Inclusión Radical $'),
        ),
        migrations.AlterField(
            model_name='order',
            name='donation_venue',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Para mejorar el espacio donde nos encontramos todo el año.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Donaciones a La Sede $'),
        ),
    ]
