# Generated by Django 3.2.9 on 2024-04-21 06:31

from django.db import migrations


def add_first_ticket_type(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    event = Event.objects.get(active=True)

    TicketType = apps.get_model("tickets", "TicketType")
    TicketType.objects.create(
        event=event,
        name="General",
        price=69,
        price_with_coupon=49,
        ticket_count=100,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_add_2024_coupons'),
        ('events', '0003_auto_20230417_1627'),
    ]

    operations = [
        migrations.RunPython(add_first_ticket_type),
    ]
