# Generated by Django 4.2.15 on 2024-08-21 00:08

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations


def migrate_ticket_data(apps, schema_editor):
    Order = apps.get_model('tickets', 'Order')
    OrderTicket = apps.get_model('tickets', 'OrderTicket')

    # Iterate through all existing orders and create corresponding OrderTicket entries
    for order in Order.objects.all():
        if order.ticket_type:
            OrderTicket.objects.create(
                order=order,
                ticket_type=order.ticket_type,
                quantity=1  # Assuming each order had one ticket type with quantity 1
            )


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0027_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets',
                                            to='tickets.order')),
                ('ticket_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tickets.tickettype')),
            ],
        ),
        migrations.RunPython(migrate_ticket_data),
        migrations.RemoveField(
            model_name='order',
            name='ticket_type',
        ),
    ]
