# Generated by Django 4.2.15 on 2024-08-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_remove_order_ticket_type_orderticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_tickets', to='tickets.tickettype'),
        ),
    ]
