# Generated by Django 4.2.15 on 2024-08-22 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_max_tickets_per_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0029_alter_orderticket_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('volunteer_ranger', models.BooleanField(verbose_name='Rangers')),
                ('volunteer_transmutator', models.BooleanField(verbose_name='Transmutadores')),
                ('volunteer_umpalumpa', models.BooleanField(verbose_name='CAOS (Desarme de la Ciudad)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.event'),
        ),
        migrations.CreateModel(
            name='NewTicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_to_email', models.CharField(max_length=320)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.newticket')),
                ('tx_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferred_tickets', to=settings.AUTH_USER_MODEL)),
                ('tx_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.order'),
        ),
        migrations.AddField(
            model_name='newticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
    ]
