# Generated by Django 4.2.15 on 2024-08-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newticket',
            name='volunteer_ranger',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rangers'),
        ),
        migrations.AlterField(
            model_name='newticket',
            name='volunteer_transmutator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transmutadores'),
        ),
        migrations.AlterField(
            model_name='newticket',
            name='volunteer_umpalumpa',
            field=models.BooleanField(blank=True, null=True, verbose_name='CAOS (Desarme de la Ciudad)'),
        ),
    ]
