# Generated by Django 4.2.15 on 2024-08-29 00:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_newticket_created_at_newticket_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('payload', jsonfield.fields.JSONField()),
            ],
        ),
    ]
