# Generated by Django 4.2.15 on 2024-08-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_messageidempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ONLINE_PURCHASE', 'Compra Online'), ('CASH_ONSITE', 'Efectivo'), ('CAMPS', 'Camps'), ('ART', 'Arte'), ('OTHER', 'Otro')], default='ONLINE_PURCHASE', max_length=20),
        ),
    ]
