# Generated by Django 4.2.15 on 2024-10-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0037_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='generated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
