# Generated by Django 4.2.15 on 2024-10-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0038_directtickettemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directtickettemplate',
            options={'verbose_name': 'Bono dirigido', 'verbose_name_plural': 'Config Bonos dirigidos'},
        ),
        migrations.AddField(
            model_name='directtickettemplate',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directtickettemplate',
            name='name',
            field=models.CharField(help_text='Descripción y/o referencias', max_length=255),
        ),
    ]
