# Generated by Django 4.2.15 on 2024-10-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0038_order_generated_by"),
    ]
    database_operations = [migrations.AlterModelTable("Profile", "user_profile_profile")]

    state_operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
