# Generated by Django 4.2.15 on 2024-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newticket',
            options={'verbose_name': 'Ticket'},
        ),
        migrations.AlterModelOptions(
            name='newtickettransfer',
            options={'verbose_name': 'Ticket transfer'},
        ),
    ]
