# Generated by Django 4.2.15 on 2024-10-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_alter_order_order_type'),
        ('tickets', '0039_alter_directtickettemplate_options_and_more'),
    ]

    operations = [
    ]
