# Generated by Django 4.2.15 on 2024-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_merge_20241022_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='is_direct_type',
            field=models.BooleanField(default=False),
        ),
    ]
