# Generated by Django 4.2.15 on 2024-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_tickettype_is_direct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtickettemplate',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignados')], default='AVAILABLE', max_length=20),
        ),
    ]
