# Generated by Django 4.2.15 on 2024-10-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_order_generated_by'),
        ('tickets', '0042_directtickettemplate_status'),
    ]

    operations = [
    ]
