# Generated by Django 4.2.15 on 2024-10-28 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0043_merge_20241027_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newticket',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
