# Generated by Django 4.2.15 on 2024-10-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_alter_newticket_options_and_more'),
        ('tickets', '0044_alter_newticket_holder'),
    ]

    operations = [
    ]
