# Generated by Django 4.2.15 on 2024-04-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_alter_newticket_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ] 