# Generated by Django 4.2.15 on 2024-10-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_merge_20241028_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directtickettemplate',
            name='used',
        ),
    ]
