# Generated by Django 4.2.15 on 2024-11-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_remove_directtickettemplate_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directtickettemplate',
            options={'permissions': [('admin_volunteers', 'Can admin Volunteers')], 'verbose_name': 'Bono dirigido', 'verbose_name_plural': 'Config Bonos dirigidos'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_sell_tickets', 'Can sell tickets in Caja')]},
        ),
    ]
