# Generated by Django 4.2.15 on 2024-11-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0049_directtickettemplate_amount_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='generated_by',
            new_name='generated_by_admin_user',
        ),
    ]
