# Generated by Django 4.2.15 on 2024-11-21 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_volunteers_enabled_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0050_rename_order_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_tickets', to='tickets.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='events.event'),
        ),
        migrations.AlterField(
            model_name='order',
            name='generated_by_admin_user',
            field=models.ForeignKey(blank=True, help_text='Usuario admin que generó la orden', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='generated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
