# Generated by Django 4.2.15 on 2025-04-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_newticket_used'),
        ('tickets', '0051_alter_newticket_order_alter_order_event_and_more'),
    ]

    operations = [
    ]
