# Generated by Django 4.2.15 on 2024-03-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_merge_20250423_1914'),
    ]

    # `is_used` was already added by tickets.0045_newticket_used.
    operations = []
