# Generated by Django 4.2.15 on 2024-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_merge_20250423_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ] 