# Generated by Django 4.2.15 on 2025-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0054_add_is_used_to_newticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='cardinality',
            field=models.IntegerField(blank=True, help_text='Optional ordering number for ticket types', null=True),
        ),
    ]
