# Generated by Django 4.2.24 on 2025-09-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0055_tickettype_cardinality'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net amount received after fees', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processor_callback',
            field=models.JSONField(blank=True, help_text='Payment processor callback data', null=True),
        ),
    ]
