# Generated by Django 4.2.24 on 2025-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0056_order_net_received_amount_order_processor_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ticket was marked as used', null=True),
        ),
    ]
