# Generated by Django 4.2.24 on 2025-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0057_add_used_at_to_newticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the ticket usage', null=True),
        ),
        migrations.AddField(
            model_name='newticket',
            name='photos',
            field=models.JSONField(blank=True, help_text='Photos related to the ticket usage', null=True),
        ),
    ]
