# Generated by Django 4.2.24 on 2025-09-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0059_remove_newticket_photos_ticketphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='scanned_by',
            field=models.ForeignKey(blank=True, help_text='User who scanned/marked the ticket as used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
