# Generated by Django 4.2.24 on 2025-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0060_add_scanned_by_to_newticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='ignore_max_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='show_in_caja',
            field=models.BooleanField(default=True),
        ),
    ]
