# Generated by Django 4.2.24 on 2025-10-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0061_tickettype_ignore_max_amount_tickettype_show_in_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='color',
            field=models.CharField(blank=True, default='6633ff', max_length=6),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='emoji',
            field=models.CharField(blank=True, default='🖕', max_length=255),
        ),
    ]
