# Generated by Django 4.2.24 on 2025-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0062_make_color_emoji_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='volunteer_price',
            field=models.BooleanField(default=False, help_text='Precio para voluntarios'),
        ),
    ]
