# Generated by Django 4.2.24 on 2025-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0063_tickettype_volunteer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtickettemplate',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del usuario para asignar el bono', max_length=254, null=True),
        ),
    ]
