# Generated by Django 4.2.24 on 2025-11-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_directtickettemplate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directtickettemplate',
            name='origin',
            field=models.CharField(
                choices=[
                    ('CAMP', 'Camp'),
                    ('VOLUNTARIOS', 'Voluntarios'),
                    ('ARTE', 'Arte'),
                    ('ORGANIZACION', 'Organizacion')
                ],
                default='CAMP',
                max_length=20
            ),
        ),
    ]
