# Generated by Django 4.2.24 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_add_organizacion_origin_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='volunteer_mad',
            field=models.BooleanField(blank=True, null=True, verbose_name='MAD - Para brindar apoyo en el movimiento de obras de arte y sus partes durante FA.'),
        ),
    ]

