# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_alter_order_dni_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='holder_left',
            field=models.BooleanField(default=False, help_text='True if the holder was marked as having left the venue (salió); can be set back to False when they return (volvió a entrar)'),
        ),
    ]
