# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0068_add_holder_left_to_newticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='newticket',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the holder was marked as having left the venue', null=True),
        ),
    ]
