# Generated by Django 4.2.15 on 2026-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0070_tickettype_do_not_show_in_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('INTERNATIONAL_TRANSFER', 'Transferencia Internacional'), ('LOCAL_TRANSFER', 'Transferencia Local'), ('ONLINE_PURCHASE', 'Compra Online'), ('CASH_ONSITE', 'Efectivo'), ('MP_QR_CAJA', 'Mercado Pago QR (Caja)'), ('MP_POINT_CAJA', 'Mercado Pago Postnet (Caja)'), ('OTHER', 'Otro')], default='ONLINE_PURCHASE', max_length=32),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_count',
            field=models.IntegerField(blank=True, help_text='Deprecated: usar stock en caja.EventProductStock', null=True),
        ),
    ]
