name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zappa boto3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Download .env.dev from S3
      run: |
        aws s3 cp s3://faprivate/envs/.env.dev .env.dev

    - name: Update Zappa environment variables
      run: |
        python update_zappa_envs.py dev

    - name: Zappa Deploy or Update
      run: |
        if zappa update dev; then
          echo "Zappa update completed successfully"
        else
          echo "Zappa update failed, attempting redeploy"
          zappa undeploy dev
          zappa deploy dev
