name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Download env.dev from S3 and Deploy
        run: |
          aws s3 cp s3://faprivate/envs/env.dev env.dev
          python update_zappa_envs.py dev
          zappa update dev

      - name: Run Migrations
        run: |
          zappa manage dev migrate
